server:
  port: ${PORT}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  doc:
    swagger-ui:
      disable-swagger-default-url: true
      path: /swagger
  datasource:
    url: ENC(${URL_DB})
    username: ENC(${USERNAME_DB})
    password: ENC(${PSS})
    driver-class-name: ${DRIVE}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(${EMAIL})
    password: ENC(${PW})
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

extrenal:
  url-api-container: ${EXTERNAL_API_URL}

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${JASYPT_ENCRYPTOR}
